In [4]:
from sklearn import datasets
irosdata = datasets.load_iris()

In [5]:
irosdata["feature_names"][0]

'sepal length (cm)'

In [6]:
irosdata.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [73]:
irosdata['target_names']#index 2 = 'virgininca'

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [80]:
valueofidex = np.where(irosdata['target_names']=='virginica')

In [82]:
valueofidex[0]


array([2], dtype=int64)

In [75]:
irosdata.target_names.index('virginica')

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [42]:
result_dex = np.where(irosdata.target==2)#remove

In [46]:
x1 = irosdata.target
x2 = np.delete(x1,result_dex)
x2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
bothdata = np.delete(bothdata,result_dex)


array([1.4, 3.5, 1.4, 3. , 1.3, 3.2, 1.5, 3.1, 1.4, 3.6, 1.7, 3.9, 1.4,
       3.4, 1.5, 3.4, 1.4, 2.9, 1.5, 3.1, 1.5, 3.7, 1.6, 3.4, 1.4, 3. ,
       1.1, 3. , 1.2, 4. , 1.5, 4.4, 1.3, 3.9, 1.4, 3.5, 1.7, 3.8, 1.5,
       3.8, 1.7, 3.4, 1.5, 3.7, 1. , 3.6, 1.7, 3.3, 1.9, 3.4, 1.6, 3. ,
       1.6, 3.4, 1.5, 3.5, 1.4, 3.4, 1.6, 3.2, 1.6, 3.1, 1.5, 3.4, 1.5,
       4.1, 1.4, 4.2, 1.5, 3.1, 1.2, 3.2, 1.3, 3.5, 1.4, 3.6, 1.3, 3. ,
       1.5, 3.4, 1.3, 3.5, 1.3, 2.3, 1.3, 3.2, 1.6, 3.5, 1.9, 3.8, 1.4,
       3. , 1.6, 3.8, 1.4, 3.2, 1.5, 3.7, 1.4, 3.3, 4.4, 3. , 4.8, 2.8,
       5. , 3. , 4.5, 2.9, 3.5, 2.6, 3.8, 2.4, 3.7, 2.4, 3.9, 2.7, 5.1,
       2.7, 4.5, 3. , 4.5, 3.4, 4.7, 3.1, 4.4, 2.3, 4.1, 3. , 4. , 2.5,
       4.4, 2.6, 4.6, 3. , 4. , 2.6, 3.3, 2.3, 4.2, 2.7, 4.2, 3. , 4.2,
       2.9, 4.3, 2.9, 3. , 2.5, 4.1, 2.8, 6. , 3.3, 5.1, 2.7, 5.9, 3. ,
       5.6, 2.9, 5.8, 3. , 6.6, 3. , 4.5, 2.5, 6.3, 2.9, 5.8, 2.5, 6.1,
       3.6, 5.1, 3.2, 5.3, 2.7, 5.5, 3. , 5. , 2.5, 5.1, 2.8, 5.

In [48]:
x1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [49]:
result_dex

(array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149], dtype=int64),)

In [50]:
petallenidex = irosdata.feature_names.index('petal length (cm)')

In [51]:
sepawididex = irosdata.feature_names.index('sepal width (cm)')

In [52]:
bothdata = irosdata.data[:, [petallenidex,sepawididex] ]

In [53]:
# bothdata = np.array(bothdata)
# firstdata = list(bothdata[:,[0]])
# seconddata = list(bothdata[:,[0]])


# firstdata = bothdata[:,[0]].tolist()
# seconddata = bothdata[:,[1]].tolist()



# bothdata = list(bothdata)
bothdata = bothdata.tolist()
bothdata

[[1.4, 3.5],
 [1.4, 3.0],
 [1.3, 3.2],
 [1.5, 3.1],
 [1.4, 3.6],
 [1.7, 3.9],
 [1.4, 3.4],
 [1.5, 3.4],
 [1.4, 2.9],
 [1.5, 3.1],
 [1.5, 3.7],
 [1.6, 3.4],
 [1.4, 3.0],
 [1.1, 3.0],
 [1.2, 4.0],
 [1.5, 4.4],
 [1.3, 3.9],
 [1.4, 3.5],
 [1.7, 3.8],
 [1.5, 3.8],
 [1.7, 3.4],
 [1.5, 3.7],
 [1.0, 3.6],
 [1.7, 3.3],
 [1.9, 3.4],
 [1.6, 3.0],
 [1.6, 3.4],
 [1.5, 3.5],
 [1.4, 3.4],
 [1.6, 3.2],
 [1.6, 3.1],
 [1.5, 3.4],
 [1.5, 4.1],
 [1.4, 4.2],
 [1.5, 3.1],
 [1.2, 3.2],
 [1.3, 3.5],
 [1.4, 3.6],
 [1.3, 3.0],
 [1.5, 3.4],
 [1.3, 3.5],
 [1.3, 2.3],
 [1.3, 3.2],
 [1.6, 3.5],
 [1.9, 3.8],
 [1.4, 3.0],
 [1.6, 3.8],
 [1.4, 3.2],
 [1.5, 3.7],
 [1.4, 3.3],
 [4.7, 3.2],
 [4.5, 3.2],
 [4.9, 3.1],
 [4.0, 2.3],
 [4.6, 2.8],
 [4.5, 2.8],
 [4.7, 3.3],
 [3.3, 2.4],
 [4.6, 2.9],
 [3.9, 2.7],
 [3.5, 2.0],
 [4.2, 3.0],
 [4.0, 2.2],
 [4.7, 2.9],
 [3.6, 2.9],
 [4.4, 3.1],
 [4.5, 3.0],
 [4.1, 2.7],
 [4.5, 2.2],
 [3.9, 2.5],
 [4.8, 3.2],
 [4.0, 2.8],
 [4.9, 2.5],
 [4.7, 2.8],
 [4.3, 2.9],
 [4.4, 3.0],
 [4.8, 2.8],

In [54]:
target_label = list(irosdata['target'])
target_label

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [41]:
# dataset_comb = list(zip(bothdata,target_label))
dataset_comb = np.column_stack((bothdata,target_label))
dataset_comb = dataset_comb.tolist()
dataset_comb


[[1.4, 3.5, 0.0],
 [1.4, 3.0, 0.0],
 [1.3, 3.2, 0.0],
 [1.5, 3.1, 0.0],
 [1.4, 3.6, 0.0],
 [1.7, 3.9, 0.0],
 [1.4, 3.4, 0.0],
 [1.5, 3.4, 0.0],
 [1.4, 2.9, 0.0],
 [1.5, 3.1, 0.0],
 [1.5, 3.7, 0.0],
 [1.6, 3.4, 0.0],
 [1.4, 3.0, 0.0],
 [1.1, 3.0, 0.0],
 [1.2, 4.0, 0.0],
 [1.5, 4.4, 0.0],
 [1.3, 3.9, 0.0],
 [1.4, 3.5, 0.0],
 [1.7, 3.8, 0.0],
 [1.5, 3.8, 0.0],
 [1.7, 3.4, 0.0],
 [1.5, 3.7, 0.0],
 [1.0, 3.6, 0.0],
 [1.7, 3.3, 0.0],
 [1.9, 3.4, 0.0],
 [1.6, 3.0, 0.0],
 [1.6, 3.4, 0.0],
 [1.5, 3.5, 0.0],
 [1.4, 3.4, 0.0],
 [1.6, 3.2, 0.0],
 [1.6, 3.1, 0.0],
 [1.5, 3.4, 0.0],
 [1.5, 4.1, 0.0],
 [1.4, 4.2, 0.0],
 [1.5, 3.1, 0.0],
 [1.2, 3.2, 0.0],
 [1.3, 3.5, 0.0],
 [1.4, 3.6, 0.0],
 [1.3, 3.0, 0.0],
 [1.5, 3.4, 0.0],
 [1.3, 3.5, 0.0],
 [1.3, 2.3, 0.0],
 [1.3, 3.2, 0.0],
 [1.6, 3.5, 0.0],
 [1.9, 3.8, 0.0],
 [1.4, 3.0, 0.0],
 [1.6, 3.8, 0.0],
 [1.4, 3.2, 0.0],
 [1.5, 3.7, 0.0],
 [1.4, 3.3, 0.0],
 [4.7, 3.2, 1.0],
 [4.5, 3.2, 1.0],
 [4.9, 3.1, 1.0],
 [4.0, 2.3, 1.0],
 [4.6, 2.8, 1.0],
 [4.5, 2.8

In [16]:
irosdata['target_names']#index 2 = 'virgininca'

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [17]:
x1 = irosdata.data[0, 1:3]
x1

array([3.5, 1.4])

<h3>CLASSIFICATION only between setosa and versicolor</h3>

In [19]:
import numpy as np

In [63]:
bothdata
botdata = np.array(bothdata)

In [67]:
botdata[0]

array([1.4, 3.5])

In [62]:
result_dex


(array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149], dtype=int64),)

In [71]:
botdata

array([[1.4, 3.5],
       [1.4, 3. ],
       [1.3, 3.2],
       [1.5, 3.1],
       [1.4, 3.6],
       [1.7, 3.9],
       [1.4, 3.4],
       [1.5, 3.4],
       [1.4, 2.9],
       [1.5, 3.1],
       [1.5, 3.7],
       [1.6, 3.4],
       [1.4, 3. ],
       [1.1, 3. ],
       [1.2, 4. ],
       [1.5, 4.4],
       [1.3, 3.9],
       [1.4, 3.5],
       [1.7, 3.8],
       [1.5, 3.8],
       [1.7, 3.4],
       [1.5, 3.7],
       [1. , 3.6],
       [1.7, 3.3],
       [1.9, 3.4],
       [1.6, 3. ],
       [1.6, 3.4],
       [1.5, 3.5],
       [1.4, 3.4],
       [1.6, 3.2],
       [1.6, 3.1],
       [1.5, 3.4],
       [1.5, 4.1],
       [1.4, 4.2],
       [1.5, 3.1],
       [1.2, 3.2],
       [1.3, 3.5],
       [1.4, 3.6],
       [1.3, 3. ],
       [1.5, 3.4],
       [1.3, 3.5],
       [1.3, 2.3],
       [1.3, 3.2],
       [1.6, 3.5],
       [1.9, 3.8],
       [1.4, 3. ],
       [1.6, 3.8],
       [1.4, 3.2],
       [1.5, 3.7],
       [1.4, 3.3],
       [4.7, 3.2],
       [4.5, 3.2],
       [4.9,

In [72]:
np.delete(botdata,result_dex,axis = 0)

array([[1.4, 3.5],
       [1.4, 3. ],
       [1.3, 3.2],
       [1.5, 3.1],
       [1.4, 3.6],
       [1.7, 3.9],
       [1.4, 3.4],
       [1.5, 3.4],
       [1.4, 2.9],
       [1.5, 3.1],
       [1.5, 3.7],
       [1.6, 3.4],
       [1.4, 3. ],
       [1.1, 3. ],
       [1.2, 4. ],
       [1.5, 4.4],
       [1.3, 3.9],
       [1.4, 3.5],
       [1.7, 3.8],
       [1.5, 3.8],
       [1.7, 3.4],
       [1.5, 3.7],
       [1. , 3.6],
       [1.7, 3.3],
       [1.9, 3.4],
       [1.6, 3. ],
       [1.6, 3.4],
       [1.5, 3.5],
       [1.4, 3.4],
       [1.6, 3.2],
       [1.6, 3.1],
       [1.5, 3.4],
       [1.5, 4.1],
       [1.4, 4.2],
       [1.5, 3.1],
       [1.2, 3.2],
       [1.3, 3.5],
       [1.4, 3.6],
       [1.3, 3. ],
       [1.5, 3.4],
       [1.3, 3.5],
       [1.3, 2.3],
       [1.3, 3.2],
       [1.6, 3.5],
       [1.9, 3.8],
       [1.4, 3. ],
       [1.6, 3.8],
       [1.4, 3.2],
       [1.5, 3.7],
       [1.4, 3.3],
       [4.7, 3.2],
       [4.5, 3.2],
       [4.9,